### ISSUE TITLE
Config file check

### ISSUE THREAD

**Issue by jeffmccollum** [hashicorp-services/tfm#182]
**Is your feature request related to a problem? Please describe.**
I make mistakes in the tfm config file and tfm will accept the broken config file and encounter not helpful errors. 

**Describe the solution you'd like**
When tfm runs, it will evaluate the config file, make sure it is properly parsed and give helpful corrections.

**Comment by abuxton** [comment]
## Implementation Analysis: `tfm config validate`

### Problem Summary

When a `.tfm.hcl` config file contains errors (missing required keys, malformed map entries, placeholder values, conflicting options), `tfm` either silently proceeds with empty/zero values and fails deep in an API call, or surfaces an opaque Viper/Go error. The user has no actionable feedback about what is wrong in the config file.

---

### Proposed Solution

Two complementary components:

1. **`tfm config validate`** — an explicit command a user can run at any time to validate their config file before running a migration
2. **Runtime validation** — the same validation logic runs automatically in `initConfig()` before any command executes, replacing cryptic downstream errors with clear, actionable config errors

---

### New Command: `tfm config validate`

A new `config` command group alongside `generate`, with `validate` as a subcommand:

```
tfm config validate              # validates the default .tfm.hcl in . or $HOME
tfm config validate --config /path/to/custom.hcl   # validates a specific file
```

#### File layout

```
cmd/config/
  config.go          # ConfigCmd parent (mirrors generate/generate.go pattern)
  validate.go        # validateConfigCmd + runValidation() logic
```

#### Registration in `cmd/root.go`

```go
import "github.com/hashicorp-services/tfm/cmd/config"
// ...
RootCmd.AddCommand(config.ConfigCmd)
```

---

### Validation Checks

#### 1. HCL parse check (catches syntax errors early)

Viper silently ignores parse errors in some cases. The validator re-reads the config file explicitly using the `hashicorp/hcl` parser and surfaces any HCL syntax errors as human-readable messages:

```
✗ Config file parse error: unexpected token "=" at line 5, col 3
```

#### 2. Required keys present

Checks that the six core connection keys are non-empty:

| Key | Required for |
|---|---|
| `src_tfe_hostname` | All source-side commands |
| `src_tfe_org` | All source-side commands |
| `src_tfe_token` | All source-side commands |
| `dst_tfc_hostname` | All destination-side commands |
| `dst_tfc_org` | All destination-side commands |
| `dst_tfc_token` | All destination-side commands |

```
✗ src_tfe_hostname is required but not set
✗ dst_tfc_token is required but not set
```

#### 3. Placeholder value detection

The generated template writes literal placeholder strings. Detect if users left them in:

```go
placeholders := []string{
    "Must have owner permissions",
    "An Oauth ID",
    "A github token",
    "A gitlab token",
}
```

```
✗ src_tfe_token appears to still be a placeholder value — replace with a real token
```

#### 4. Hostname format check

A very common mistake: including `https://` in the hostname field:

```
✗ src_tfe_hostname should be a hostname only, not a URL — remove "https://" prefix
```

#### 5. Map key format validation

All `*-map` keys must be `source=destination` pairs. Reuses the existing `helper.ViperStringSliceMap()` logic but with named, actionable errors:

```
✗ workspaces-map entry 3 is malformed: "ws-without-equals" — expected "source=destination" format
✗ agents-map entry 1 has empty destination: "apool-abc=" — destination value is required
```

Affected keys: `workspaces-map`, `projects-map`, `vcs-map`, `agents-map`, `varsets-map`, `ssh-map`

#### 6. Mutual exclusion checks

Config keys that conflict with each other:

```go
mutuallyExclusive := [][]string{
    {"workspaces", "workspaces-map"},
    {"projects", "projects-map"},
    {"agents-map", "agent-assignment-id"},
}
```

```
✗ "workspaces" and "workspaces-map" cannot both be set — choose one
```

#### 7. Connectivity check (optional, `--test-connectivity` flag)

When `--test-connectivity` is passed, the validator attempts a lightweight API call to both the source and destination:

```go
// calls c.SourceClient.Organizations.Read(ctx, orgName) 
// and c.DestinationClient.Organizations.Read(ctx, orgName)
```

```
✓ Source connection OK      (app.terraform.io / my-source-org)
✗ Destination connection FAILED: 401 Unauthorized — check dst_tfc_token
```

This check is opt-in because: (a) it requires valid credentials, and (b) `tfm config validate` should work offline for syntax checking.

---

### Runtime Validation (automatic on every run)

A lightweight validation step added to `initConfig()` in `cmd/root.go`, run after Viper loads the config and before any command executes.

The runtime check is intentionally narrower than the full `validate` command — it only checks what is unambiguously wrong:

```go
// In initConfig(), after viper.ReadInConfig():
if err := helper.ValidateConfigRuntime(); err != nil {
    fmt.Fprintf(os.Stderr, "Config error: %v\n", err)
    fmt.Fprintf(os.Stderr, "Run \"tfm config validate\" for a full config report.\n")
    os.Exit(1)
}
```

`ValidateConfigRuntime()` checks:
- HCL parse succeeded (viper.ReadInConfig error surfaced clearly)
- Any set `*-map` key passes format validation (catches `workspaces-map = ["no-equals"]` style mistakes immediately)
- Placeholder values in hostname/token fields

It does **not** check required-key presence at runtime because some commands (e.g. `tfm generate config`, `tfm config validate`) are valid with an empty or missing config.

---

### Implementation Plan

#### New files

| File | Purpose |
|---|---|
| `cmd/config/config.go` | `ConfigCmd` Cobra parent command |
| `cmd/config/validate.go` | `validateConfigCmd` + `runValidation()` |

#### Modified files

| File | Change |
|---|---|
| `cmd/root.go` | Import `cmd/config`, add `RootCmd.AddCommand(config.ConfigCmd)`, call `helper.ValidateConfigRuntime()` in `initConfig()` |
| `cmd/helper/validate.go` | New: `ValidateConfigRuntime()` and shared validation helpers used by both runtime and `validate` command |
| `site/docs/commands/config/validate.md` | New docs page |
| `site/docs/configuration_file/config_file.md` | Add reference to `tfm config validate` |
| `README.md` | Add `tfm config validate` to commands table |

#### Example `cmd/config/validate.go` sketch

```go
package config

import (
    "fmt"
    "strings"

    "github.com/hashicorp-services/tfm/cmd/helper"
    "github.com/hashicorp-services/tfm/tfclient"
    "github.com/spf13/cobra"
    "github.com/spf13/viper"
)

type ValidationResult struct {
    Key     string
    OK      bool
    Message string
}

var testConnectivity bool

var validateConfigCmd = &cobra.Command{
    Use:   "validate",
    Short: "Validate the tfm config file",
    Long:  "Validate the .tfm.hcl config file for syntax errors, missing keys, malformed maps, and conflicts",
    RunE: func(cmd *cobra.Command, args []string) error {
        return runValidation(testConnectivity)
    },
    PostRun: func(cmd *cobra.Command, args []string) {
        o.Close()
    },
}

func init() {
    validateConfigCmd.Flags().BoolVar(&testConnectivity, "test-connectivity", false,
        "Test API connectivity to source and destination hosts (requires valid credentials)")
    ConfigCmd.AddCommand(validateConfigCmd)
}

func runValidation(connectivity bool) error {
    results := []ValidationResult{}
    failed := false

    // 1. Config file found
    if viper.ConfigFileUsed() == "" {
        results = append(results, ValidationResult{"config-file", false, "No config file found — run \"tfm generate config\" to create one"})
        failed = true
    } else {
        results = append(results, ValidationResult{"config-file", true, fmt.Sprintf("Found: %s", viper.ConfigFileUsed())})
    }

    // 2. Required keys
    for _, key := range []string{"src_tfe_hostname", "src_tfe_org", "src_tfe_token", "dst_tfc_hostname", "dst_tfc_org", "dst_tfc_token"} {
        v := viper.GetString(key)
        if v == "" {
            results = append(results, ValidationResult{key, false, fmt.Sprintf("%s is not set", key)})
            failed = true
        } else if isPlaceholder(v) {
            results = append(results, ValidationResult{key, false, fmt.Sprintf("%s appears to be a placeholder — replace with a real value", key)})
            failed = true
        } else {
            results = append(results, ValidationResult{key, true, "OK"})
        }
    }

    // 3. Hostname URL prefix check
    for _, key := range []string{"src_tfe_hostname", "dst_tfc_hostname"} {
        v := viper.GetString(key)
        if strings.HasPrefix(v, "https://") || strings.HasPrefix(v, "http://") {
            results = append(results, ValidationResult{key, false, fmt.Sprintf("%s must be a hostname only, not a URL — remove the \"https://\" prefix", key)})
            failed = true
        }
    }

    // 4. Map format checks
    for _, mapKey := range []string{"workspaces-map", "projects-map", "vcs-map", "agents-map", "varsets-map", "ssh-map"} {
        if viper.IsSet(mapKey) {
            _, err := helper.ViperStringSliceMap(mapKey)
            if err != nil {
                results = append(results, ValidationResult{mapKey, false, fmt.Sprintf("%s: %v", mapKey, err)})
                failed = true
            } else {
                results = append(results, ValidationResult{mapKey, true, "OK"})
            }
        }
    }

    // 5. Mutual exclusion
    for _, pair := range [][2]string{
        {"workspaces", "workspaces-map"},
        {"projects", "projects-map"},
        {"agents-map", "agent-assignment-id"},
    } {
        if viper.IsSet(pair[0]) && viper.IsSet(pair[1]) {
            results = append(results, ValidationResult{pair[0]+"+"+pair[1], false, fmt.Sprintf("%q and %q cannot both be set — choose one", pair[0], pair[1])})
            failed = true
        }
    }

    // 6. Connectivity (opt-in)
    if connectivity {
        c := tfclient.GetClientContexts()
        // source ping
        _, err := c.SourceClient.Organizations.Read(c.SourceContext, c.SourceOrganizationName)
        if err != nil {
            results = append(results, ValidationResult{"source-connectivity", false, fmt.Sprintf("Source API call failed: %v", err)})
            failed = true
        } else {
            results = append(results, ValidationResult{"source-connectivity", true, fmt.Sprintf("Connected to %s / %s", c.SourceHostname, c.SourceOrganizationName)})
        }
        // destination ping
        _, err = c.DestinationClient.Organizations.Read(c.DestinationContext, c.DestinationOrganizationName)
        if err != nil {
            results = append(results, ValidationResult{"destination-connectivity", false, fmt.Sprintf("Destination API call failed: %v", err)})
            failed = true
        } else {
            results = append(results, ValidationResult{"destination-connectivity", true, fmt.Sprintf("Connected to %s / %s", c.DestinationHostname, c.DestinationOrganizationName)})
        }
    }

    // Print results
    for _, r := range results {
        if r.OK {
            o.AddMessageUserProvided(fmt.Sprintf("✓ %s", r.Key), r.Message)
        } else {
            o.AddErrorUserProvided(fmt.Sprintf("✗ %s: %s", r.Key, r.Message))
        }
    }

    if failed {
        return fmt.Errorf("config validation failed — fix the issues above and retry")
    }
    return nil
}

var placeholderSubstrings = []string{
    "Must have owner permissions",
    "An Oauth ID",
    "A github token",
    "A gitlab token",
    "A gitlab username",
    "A github username",
    "your-token-here",
}

func isPlaceholder(s string) bool {
    for _, p := range placeholderSubstrings {
        if strings.Contains(s, p) {
            return true
        }
    }
    return false
}
```

---

### Acceptance Criteria

- [ ] `tfm config validate` exits 0 and prints `✓` lines for a well-formed config
- [ ] `tfm config validate` exits non-zero and prints `✗` with actionable messages for each issue found (missing key, placeholder, malformed map, conflict)
- [ ] `tfm config validate --test-connectivity` also tests API connectivity against source and destination
- [ ] Runtime validation in `initConfig()` surfaces HCL parse errors and malformed map entries before any command runs, with a hint to run `tfm config validate`
- [ ] `tfm generate config` hint output updated to suggest running `tfm config validate` after generating
- [ ] `--config /path/to/file.hcl` flag respected (inherits from `RootCmd.PersistentFlags()`)
- [ ] `go build ./cmd/...` and `go vet ./...` pass
- [ ] Unit tests in `cmd/config/validate_test.go` cover: empty config, placeholder values, malformed map, mutual exclusion, `https://` prefix, valid config
- [ ] Docs added at `site/docs/commands/config/validate.md`
- [ ] `site/docs/configuration_file/config_file.md` references `tfm config validate`
- [ ] README commands table updated

### Related

- Builds on existing `helper.ViperStringSliceMap()` validation in `cmd/helper/helper_viper.go`
- `validateMap()` in `cmd/copy/validation.go` and `cmd/delete/validation.go` — existing runtime map validation that would be superseded/unified
- `tfm generate config` — natural counterpart; suggest validating after generating
- #61 (`TFM_LOG`) — use logging package for INFO/DEBUG output in the validate command
