### ISSUE TITLE
Workspace Notification Migration

### ISSUE THREAD

**Issue by jeffmccollum** [hashicorp-services/tfm#216]
I would like to copy notification settings when migrating a workspace from TFE/TFC and vice versa. 

Today that is not possible.

**Comment by abuxton** [comment]
## Implementation Analysis

### What is a Notification Configuration?

A notification configuration defines a webhook/email alert attached to a **workspace** or **team** that fires on selected run lifecycle events. The TFE API docs: https://developer.hashicorp.com/terraform/enterprise/api-docs/notification-configurations

---

### go-tfe Support (v1.107.0 — current in tfm)

The go-tfe library fully supports notification configurations. The relevant interface is `tfe.NotificationConfigurations` with these methods:

```go
List(ctx, subscribableID string, options *NotificationConfigurationListOptions) (*NotificationConfigurationList, error)
Create(ctx, subscribableID string, options NotificationConfigurationCreateOptions) (*NotificationConfiguration, error)
Read(ctx, notificationConfigurationID string) (*NotificationConfiguration, error)
Update(ctx, notificationConfigurationID string, options NotificationConfigurationUpdateOptions) (*NotificationConfiguration, error)
Delete(ctx, notificationConfigurationID string) error
Verify(ctx, notificationConfigurationID string) (*NotificationConfiguration, error)
```

Accessed via: `client.NotificationConfigurations.List(...)` / `.Create(...)`

#### Destination types supported
| Constant | Value |
|---|---|
| `NotificationDestinationTypeEmail` | `"email"` |
| `NotificationDestinationTypeGeneric` | `"generic"` (webhook) |
| `NotificationDestinationTypeSlack` | `"slack"` |
| `NotificationDestinationTypeMicrosoftTeams` | `"microsoft-teams"` |

#### Trigger types supported
| Constant | Value |
|---|---|
| `NotificationTriggerCreated` | `run:created` |
| `NotificationTriggerPlanning` | `run:planning` |
| `NotificationTriggerNeedsAttention` | `run:needs_attention` |
| `NotificationTriggerApplying` | `run:applying` |
| `NotificationTriggerCompleted` | `run:completed` |
| `NotificationTriggerErrored` | `run:errored` |
| `NotificationTriggerAssessmentDrifted` | `assessment:drifted` |
| `NotificationTriggerAssessmentFailed` | `assessment:failed` |
| `NotificationTriggerAssessmentCheckFailed` | `assessment:check_failure` |
| `NotificationTriggerWorkspaceAutoDestroyReminder` | `workspace:auto_destroy_reminder` |
| `NotificationTriggerWorkspaceAutoDestroyRunResults` | `workspace:auto_destroy_run_results` |
| `NotificationTriggerChangeRequestCreated` | `change_request:created` |

#### Subscribable scope — workspace vs team
`List` and `Create` are **polymorphic**: the `subscribableID` is either a workspace ID or a team ID, controlled by `SubscribableChoice`:

```go
// List for a workspace
client.NotificationConfigurations.List(ctx, workspaceID, &tfe.NotificationConfigurationListOptions{
    SubscribableChoice: &tfe.NotificationConfigurationSubscribableChoice{
        Workspace: &tfe.Workspace{ID: workspaceID},
    },
})

// List for a team
client.NotificationConfigurations.List(ctx, teamID, &tfe.NotificationConfigurationListOptions{
    SubscribableChoice: &tfe.NotificationConfigurationSubscribableChoice{
        Team: &tfe.Team{ID: teamID},
    },
})
```

> **Note:** Notification configurations are **not** directly associated with Projects. Projects contain workspaces; the notifications live on the workspace or team. There is no project-scoped notification endpoint in the TFE API.

#### TFE-only fields
- `EmailAddresses []string` — only available on self-hosted TFE, **not** on HCP Terraform. This must be handled gracefully (skip or warn if migrating TFE → HCP Terraform).
- `EmailUsers []*User` — user relations; email user IDs will differ between source and destination orgs and cannot be directly mapped without a user lookup step.

#### Token field behaviour
The `Token` field on `NotificationConfiguration` is a HMAC secret for generic webhooks. It is **write-only** — the API never returns its value. When copying, `Token` on the source will always be empty. The copy operation should warn the operator and optionally accept a replacement token via config or flag.

---

### Implementation Plan

#### New file: `cmd/copy/workspaces-notifications.go`

Pattern mirrors `workspaces-run-triggers.go` exactly:

1. Call `getSrcWorkspacesCfg(c)` to get source workspace list (respects `workspaces` / `workspaces-map` config keys)
2. For each source workspace, call `c.SourceClient.NotificationConfigurations.List(...)` with `SubscribableChoice.Workspace`
3. Resolve the destination workspace ID via `getWorkspaceId(...)`
4. For each source notification config, check if one with the same `Name` already exists in destination
5. If not, call `c.DestinationClient.NotificationConfigurations.Create(...)` with mapped options
6. Warn if `Token` is empty (cannot be migrated), warn if `EmailAddresses` is set and destination is HCP Terraform

```go
func copyWorkspaceNotifications(c tfclient.ClientContexts) error {
    log := logging.NewLogger("copy.notifications")
    srcWorkspaces, err := getSrcWorkspacesCfg(c)
    // ... for each workspace, list + create pattern
}
```

#### Wiring into `workspaces.go`

Add a new bool flag `notifications` and dispatch case:

```go
// In var block:
notifications bool

// In init():
workspacesCopyCmd.Flags().BoolVarP(&notifications, "notifications", "", false, "Copy workspace notification configurations")

// In RunE switch:
case notifications:
    return copyWorkspaceNotifications(tfclient.GetClientContexts())
```

#### CLI usage
```bash
tfm copy workspaces --notifications
tfm copy workspaces --notifications --config .tfm.hcl
```

#### Team notifications (optional scope extension)
The go-tfe `List`/`Create` also support team-scoped notifications via `SubscribableChoice.Team`. This could be added as a separate `tfm copy teams --notifications` flag on `teamCopyCmd`, following the same pattern. This is lower priority than workspace notifications.

---

### Caveats and edge cases to handle

| Scenario | Handling |
|---|---|
| Notification already exists with same name in destination | Skip + info log |
| `Token` field (HMAC secret) — API never returns value | Warn operator; copy with empty token; optionally accept `--notification-token` flag |
| `EmailAddresses` set on TFE source, destination is HCP Terraform | Warn and skip email addresses field |
| `EmailUsers` — user IDs differ between orgs | Skip users relation; log warning that email user membership must be reconfigured manually |
| `NotificationDestinationTypeEmail` with no email addresses | Copy as-is; users must add members manually in destination |
| Source workspace does not exist in destination yet | Skip with warning (workspace must be migrated first) |

---

### Acceptance Criteria

- [ ] `tfm copy workspaces --notifications` copies all notification configurations for each source workspace to the matching destination workspace
- [ ] Skips configs that already exist in destination (idempotent)
- [ ] Warns when `Token` field is empty (cannot be migrated) and continues
- [ ] Warns when `EmailAddresses` are present and destination is HCP Terraform
- [ ] Respects `workspaces` and `workspaces-map` config keys to scope which workspaces are processed
- [ ] INFO log lines emitted for each notification created/skipped (compatible with `--verbose` / `TFM_LOG=INFO`)
- [ ] Unit tests cover: list error, create success, create skip-if-exists, token warning, email-address warning
- [ ] Docs page `site/docs/commands/copy/workspaces.md` updated with `--notifications` flag
- [ ] `go build ./cmd/...` and `go vet ./...` pass

### Related issues
- #61 (logging) — `--verbose` flag and `TFM_LOG` are already implemented and should be used here
